install autoconf
install autoenv
install automake
install awscli
install bash-completion
install cask
install cctools
install curl
install deis
install deisctl
install docker
install gcutil
install gdbm
install gettext
install git
install gnu-getopt
install gnupg
install gpgtools
install heimdal
install java
install kubernetes-cli
install kubernetes-helm
install libgpg-error
install libksba
install libtool
install libyaml
install maven
install mr
install nmap
install openssl
install packer
install pkg-config
install pyenv
install pyenv-virtualenv
install pyenv-virtualenvwrapper
install python
install python3
install rbenv
install readline
install ruby-build
install sqlite
install terraform
install tree
install vagrant
install vagrant-completion
install virtualbox
install wakeonlan
install watch
install whatmask
install xz
